feat(interface): Initial dev tools & Sidebar Concepts (#19)
* feat(interface/sidebar): Add the Sidebar and relative components

* fix(github/actions): Execute frontend tests on the frontend directory

* chore(ts): Resolve Typescript eslint errors

* docs(readme): Add Logo on header line

* feat(interface): Add new icon and favicon

* docs(storybook): Add Storybook for the component documentation

* chore: Add Jest to test frontend

* feat(interface/sidebar): Add the Sidebar and relative components

* fix(github/actions): Execute frontend tests on the frontend directory

* chore(ts): Resolve Typescript eslint errors

* feat(interface): Add new icon and favicon

* docs(storybook): Add Storybook for the component documentation

* chore: Add Jest to test frontend

* chore: Ignore coverage

* test: Remove coverage from git

* test: Setup Cypress and Jest

* test(snapshot): Add Tooltop snapshot test

* test: Add Tooltip test unit

* docs: Add Docs to Sidebar and Tooltip components

* chore: ✨ Make js pretty

* test: Test default export of Tooltip

* test(github/actions): Add Coverage Threshold for frontend tests

diff --git a/.github/workflows/frontend-tests.yaml b/.github/workflows/frontend-tests.yaml
--- a/.github/workflows/frontend-tests.yaml
+++ b/.github/workflows/frontend-tests.yaml
@@ -9,6 +9,10 @@ on:
     paths:
     - 'web/ui/**'
 
+defaults:
+  run:
+    working-directory: 'web/ui'
+
 jobs:
   linters:
     name: Frontend Linters 🕹
@@ -38,3 +42,44 @@ jobs:
 
     - name: Prettier
       run: yarn style:prettier
+  tests:
+    name: Frontend Tests 🕹
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout project
+      uses: actions/checkout@v2
+
+    - name: Setup node
+      uses: actions/setup-node@v2.1.2
+      with:
+        node-version: 16
+
+    - name: Cache node_modules
+      uses: actions/cache@v2
+      with:
+        path: ~/.npm
+        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+        restore-keys: |
+          ${{ runner.os }}-node-
+
+    - name: Install dependencies
+      run: yarn install --frozen-lockfile
+
+    - name: Jest
+      run: yarn test:ci
+
+    - name: Quality Gate - Test coverage shall be above threshold
+      env:
+          TESTCOVERAGE_THRESHOLD: 80
+      run: |
+        echo "Quality Gate: checking test coverage is above threshold ..."
+        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+        totalCoverage=`cat coverage/coverage-summary.json | jq '.total.statements.pct'`
+        echo "Current test coverage : $totalCoverage %"
+        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+            echo "OK"
+        else
+            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            echo "Failed"
+            exit 1
+        fi
